### ISSUE TITLE
Initial ideas for CLI commands

### ISSUE THREAD

**Issue by eduardolundgren** [launchpad-project/cli#1]
```
# launchpad -h
Launchpad Command Line Interface
Version 0.0.1
Copyright 2016 Liferay, Inc.
http://liferay.io

Usage:
  launchpad [command] [--flags]

Available Commands:
  info          Displays information about current app directory
  set           Configure Launchpad settings for current app directory
  deploy     Deploys a Launchpad app
  update     Updates this tool to the latest version
  version    Gets the Command Line Tools version

Use "launchpad [command] --help" for more information about a command.
```

Let's assume you have a folder that represents your app:
`cd ~/Projects/app`

1) `launchpad info`
```
Application: App
Description: This app is very cool and do things you can't imagine!
Domain: app.liferay.io
Services:
   /service1 - Displays service description. (java)
   /service2 - Displays service description. (node)
```

Info command reads a file inside root folder of the app called `.launchpad.json`.

2) `launchpad set domain customdomain.com`

Set command writes a file inside root folder of the app called `.launchpad.json`.

3) `launchpad deploy`
```
Deploying to customdomain.com...
/service1 ✓
/service2 ✓
You app is ready!
```

 `launchpad deploy service1`
```
Deploying customdomain.com...
/service1 ✓
You app is ready!
```

4) `launchpad update`
```
Found new command line version (0.0.2)
Updating...
Done
```

5) `launchpad version`
```
0.0.2
```

**Comment by henvic** [comment]
I have had a talk with @eduardolundgren, here is a summary:

* most Launchpad CLI commands should be called from inside a project. Exceptions (such as for a hypothetical command that creates a new project) MUST be whitelisted on the setup phase to avoid failing due to environment assertion.
* Use `launchpad config` similar to `git config`, including the --global for editing global configuration file and autocomplete feature, instead of `launchpad set`.
* CLI commands SHOULD follow Unix tradition, such as not writing feedback on success for obvious commands where failure is unlikely and being noise when errors does happen.
* Deploy -> push

**Comment by igorspasic** [comment]
> Let's assume you have a folder that represents your app:

Is this a working folder where developer is building the app? Or like any folder that may contain eg only a distribution pod?

> launchpad info

Having APP folder here is not of importance IMHO. Instead, we would need a config file that _describes_ the application, and CLI should read this file. Such config file should not be hidden, of course. Default name may be `launchpad-app.json`. Of course, user may set the custom name with:

    launchpad --app <file-name> ...

`info` command would simply read most relevant data from this file.

Also - if there is NO such file, we should assume that we are in single-service app.

> deploying

This is tricky. Sometimes you want to deploy a pod. Sometimes you want to send just config files for one service - in other words, there is no reason to send whole binaries every time. We should somehow distinguish these two. For example, we may store latest timestamps in some hidden file and use `--force` if we really want to push everything to the server

> Undeploy

We should also be able to undeploy something: service(s) or the whole app

**Comment by henvic** [comment]
Oh, actually for this alpha release we probably have deploy ready just yet.

That said I think we must do our best to upload only diffs and work hard on avoiding, say, a small 200 lines change to end up as a 10MB diff. It might not few so bad but it can add up pretty fast.

I think our best options for deploying are to do so over git and Torrent. Git for small and non-critical setups, and Torrent for supporting large and critical operations. I guess we better don't support any other deployment systems besides these two.

Also, we should eventually version our deploy states to facilitate rolling back, and so on, and provide a way to slowly deploy when desired (i.e., [Move Fast and Fix Things](http://githubengineering.com/move-fast/)) and destroy services.

# Reference
[murder](https://github.com/lg/murder)
[Exclusive: a behind-the-scenes look at Facebook release engineering](http://arstechnica.com/business/2012/04/exclusive-a-behind-the-scenes-look-at-facebook-release-engineering/)

**Comment by henvic** [comment]
I have spent most of the last days working on a prototype.

It's taking form and you can try it already.
https://github.com/launchpad-project/cli (checkout branch: prototype)

Next steps for the prototype:
1. remove dependency on viper (not helping as I expected)
2. fix code quality issues (missing docs, duplicate code, etc)
3. write test code for the existing / future application code

I haven't written any test code just yet because I was trying lots of such very quickly (as I said, it's a prototype), but no worries... It's not my first time writting Go code. Here is an example of code I have written in Go and are well tested, if you want to check out some Go test code examples: [picel](https://github.com/henvic/picel).

# Easy & fast way to try it out
1. follow the [Getting Started](https://golang.org/doc/install) Go instructions (you can shortcut a little bit by using `brew install go` if you use brew
2. `go get -v github.com/launchpad-project/cli`
3. `cd ~/gocode/src/github.com/launchpad-project/cli`
4. `git checkout prototype`
5. `go build`
6. **`./cli`**

## Hack I am using and might help you try to do some changes
1. add `alias launchpad="go run $HOME/gocode/src/github.com/launchpad-project/cli/main.go $1"` on your ~/.zshrc
3. `source ~/.zshrc` to refresh your terminal (or reopen it)
4. type `launchpad` on your terminal

It doesn't run fast and I am sure I am going to run into problems by using it eventually, but it's working fine for me so far.

## References
[The Go Programming Language](https://golang.org/)
[How to Write Go Code](https://golang.org/doc/code.html)

**Comment by eduardolundgren** [comment]
The pull request of the prototype looks very clean even though I am not very familiar with Go code. Good job! Today will try to run it locally to see how it feels.

**Comment by cirocosta** [comment]
Awesome! I'll be taking a look today as well!

**Comment by cirocosta** [comment]
Thanks for the detailed instructions, some minor fixes: 
- after `brew install go` one must also set `$GOPATH` env variable;
- step 3 would then take the form of `cd $GOPATH/src/github.com/launchpad-project/cli`

**Comment by cirocosta** [comment]
ops

**Comment by henvic** [comment]
Oops, it was a typo. Use the -t flag to install all required dependencies as well:
`go get -t github.com/launchpad-project/cli`

I have also noticed a failure is happening when the config file doesn't exist anymore. I am working on fixing this.

Here are two config files you can try:

**.launchpad.json on my ~:**
```
{
    "endpoint": "http://liferay.io",
    "password": "foo",
    "username": "xo"
}
```

**launchpad.json on a project directory:**
```
{
    "name": "Sample",
    "description": "This app is very cool and do things you can't imagine!",
    "domain": "app.liferay.io",
    "services": [
    	{
    		"name": "jservices",
    		"description": "Java services layer"
		},
		{
			"name": "fe",
			"description": "Front-end layer"
		}
    ]
}
```

**Comment by eduardolundgren** [comment]
Let us know when it's fixed. Thx.

**Comment by zenorocha** [comment]
Looks good! What about `login`?

Have you guys considered using Git like Heroku Toolbelt does?

https://devcenter.heroku.com/articles/heroku-command
https://github.com/heroku/toolbelt

**Comment by henvic** [comment]
@zenorocha, login instead of auth or haven't you seen the auth command?

**Comment by henvic** [comment]
If you mean using ssh keys, yeah! We have considered this.

If we support it on our servers we can use it there easily and will even allow browsers to use it as well (which I expect to start to become common as a safety measure on the web anytime).

**Comment by zenorocha** [comment]
I haven't seen `auth` on eduardo's first post... but renaming to login makes it easier to understand imo.

When I said using Git I don't mean ssh keys, I mean Git. That would help in many ways, like GitHub integration and no more file diff calculations.

**Comment by zenorocha** [comment]
Try using Heroku and you'll get what I mean.

**Comment by henvic** [comment]
Hi everyone,

I have pushed some changes to master.

You can install go (remember to export GOPATH=$HOME/gocode or wherever you'd prefer your Go code to be installed).



go get -u -t github.com/launchpad-project/cli

https://gobuilder.me/github.com/launchpad-project/cli
